# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - viivtest1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://viivtest1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4b77445138684a94b764cdfdff3fab36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a9ac49a6f73c444fb8bb2c26486a5c21 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: viivtest1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b77445138684a94b764cdfdff3fab36 }}/viivtestapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'viivtest1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c19d96dc3e8e41c6bf7febe5878424fc }}
        images: 'viivtest1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4b77445138684a94b764cdfdff3fab36 }}/viivtestapp:${{ github.sha }}'